### ISSUE TITLE
Create view and subscription for single service

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/dipor-dashboard#106]
Create a template and subscription that allows building single service summary view. Refer to requirements document for details on the view.

Definition of done
---
* [x] Single service summary template exists.
* [x] Template contains single service subscription.
* [ ] Template contains logic to show different content based on user status.
  * [ ] Where desirable, registered users and PO  see the same content.

**Comment by frenchbread** [comment]
I've added basic service view. How service path (url) supposed to look like in an open question. Since service schema contains reference only to parent department (without reference to organiaztion), it's quite problematic to fire up breadcrumb for service view. Would be cool to have some help here :)

So far, looks like this: 
![screen shot 2016-03-24 at 00 31 42](https://cloud.githubusercontent.com/assets/2122679/14003038/733806fe-f158-11e5-9270-93eb5e8bba5a.png)
