### ISSUE TITLE
Add share button to service page

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/dipor-dashboard#194]
Add a share button to platform pages, such as the Service page. Use an existing 'share' library, so that we do not need custom development hours for this.

# Resources
- [CarrotShare](https://sharebutton.co/) is an elegant, privacy-protecting share button with supports for multiple social media

# Definition of done
- [ ] CarrotShare button is added to Service page.
- [ ] When sharing via CarrotShare button, the link is shown  as expected.

**Comment by Nazarah** [comment]
I'd co pilot

**Comment by Nazarah** [comment]
Is it possible to make the share option with one click?
with the Carrot Share, you need to click the share button in order to see the platforms you wish to share into.
So for making more visibility, I was considering the idea of making the social media icons appear in the first place rather clicking on the share button.

**Comment by brylie** [comment]
Yes, it is possible. Some related considerations
- how many page elements does a person need to see on the service page?
  - how would the additional color and icons affect visual prominence of other page elements?
- what is the primary goal the 'service' view is providing the end user?
  - how does each social media channel promote or detract the primary goal of the'service' page?
- how relevant are each of the social network icon buttons to the service page?
- how difficult is it to click 'share' and then select a social channel?

**Comment by Nazarah** [comment]
1. If you are considering limiting your social media platform to 7 it is easily displayable.
More than seven can be hidden beneath a button click
2. the icons won't be taking majority portion of the page.
they are usually places within some corner and the colors areself are subdued.
So you don't need to worry about the,
3. And relevancy may differ base on what social media is the user habituated to.
I don't user tweeter, but someone may use.
And it is not about considering the how social media is helpful here about content sharing.
It is about the portal providing option to share about something.
The promotion depends on how shared content is viewed and regarded and how many times the relevant user is working with the service.

This issue was a simple visibility idea, nothing else.

**Comment by brylie** [comment]
Here are two screenshots demonstrating how the 'service' page would look with:

- a 'Share' button
- multiple button/icons for sharing channels

![dipor-serviceview-singlesharebutton](https://cloud.githubusercontent.com/assets/17307/15010483/eed85cc0-11f4-11e6-8572-51386eb412b7.png)

![dipor-serviceview-multiplesharebuttons](https://cloud.githubusercontent.com/assets/17307/15010499/f38f166e-11f4-11e6-831a-b44327d72115.png)

**Comment by brylie** [comment]
We can override styles and control the layout of the carrot share plugin, including possibly showing the icons by default. However, the overrides would go 'against' the grain of the plugin, introducing additional effort and maintenance burden. Whereas, the carrot share plugin is rather simple to use, if we just accept some of the original developers' decisions, namely clicking a single 'share' button to toggle visibility of the social network selection.

**Comment by frenchbread** [comment]
A suggestion in terms of design: What about if we add social buttons to the bottom of the page? Current approach looks to messy I think.

**Comment by brylie** [comment]
Alright, we could figure out alternative placements. Where specifically are you thinking @frenchbread?

**Comment by frenchbread** [comment]
It's quite common approach to place social buttons between the actual footer and main container that hold content.

**Comment by brylie** [comment]
Alright, perhaps the share buttons could be part of our mainLayout, so they appear site-wide then.

**Comment by brylie** [comment]
I will try again with, and without, the buttons visible. This may be a good compromise, since the placement near the bottom reduces the emphasis of the buttons.

**Comment by frenchbread** [comment]
But as I just realised, on the screenshots there is a "share" buttons that toggles social buttons to popup.

**Comment by frenchbread** [comment]
Good point.
